name: "\U0001F41E Bug Report"
description: Report an issue
title: '[Bug]: '
labels:
  - 'bug'
body:
  - type: textarea
    id: issue-description
    attributes:
      label: Describe the issue
      description: A clear description of what the issue is. If you intend to submit a PR for this issue, please indicate. Thanks!
      placeholder: Issue desription
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: What did you expect to happen?
      description: A brief description what you thought should happen instead.
      placeholder: Expected behaviour
    validations:
      required: true
  - type: checkboxes
    id: checked-existing-issues
    attributes:
      label: Have you checked that the issue has not already been raised?
      options:
        - label: I did not find any similar issues
          required: true
